{
	"version": 1749234982,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/backgroundgame-sheet0.png",
		"images/bgobjekgambar2-sheet0.png",
		"images/bgobjekhurufacak-sheet0.png",
		"images/hitam-sheet0.png",
		"images/level-sheet0.png",
		"images/level-sheet1.png",
		"images/level-sheet2.png",
		"images/level-sheet3.png",
		"images/level-sheet4.png",
		"images/level-sheet5.png",
		"images/level-sheet6.png",
		"images/level-sheet7.png",
		"images/level-sheet8.png",
		"images/bar-sheet0.png",
		"images/spritefont.png",
		"images/huruf_drop-sheet0.png",
		"images/huruf_drop-sheet1.png",
		"images/huruf_drop-sheet2.png",
		"images/huruf_drop-sheet3.png",
		"images/huruf_drop-sheet4.png",
		"images/huruf_drop-sheet5.png",
		"images/huruf_drop-sheet6.png",
		"images/huruf_drop-sheet7.png",
		"images/huruf_drop-sheet8.png",
		"images/huruf_drop-sheet9.png",
		"images/huruf_drop-sheet10.png",
		"images/huruf_drop-sheet11.png",
		"images/huruf_drop-sheet12.png",
		"images/huruf_drop-sheet13.png",
		"images/huruf_drop-sheet14.png",
		"images/huruf_drop-sheet15.png",
		"images/huruf_drop-sheet16.png",
		"images/huruf_drop-sheet17.png",
		"images/huruf_drop-sheet18.png",
		"images/huruf_drop-sheet19.png",
		"images/huruf_drop-sheet20.png",
		"images/huruf_drop-sheet21.png",
		"images/huruf_drop-sheet22.png",
		"images/huruf_drop-sheet23.png",
		"images/huruf_drop-sheet24.png",
		"images/huruf_drop-sheet25.png",
		"images/huruf_drop-sheet26.png",
		"images/huruf_drak-sheet0.png",
		"images/kembali-sheet0.png",
		"images/kembali-sheet1.png",
		"images/kembali-sheet2.png",
		"images/hore-sheet0.png",
		"images/bintangcopy-sheet0.png",
		"images/kalah2-sheet0.png",
		"images/home-sheet0.png",
		"images/background-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite-sheet2.png",
		"images/sprite-sheet3.png",
		"images/sprite-sheet4.png",
		"images/sprite-sheet5.png",
		"images/sprite-sheet6.png",
		"images/sprite-sheet7.png",
		"images/sprite-sheet8.png",
		"images/maju-sheet0.png",
		"images/mundur-sheet0.png",
		"images/keluar-sheet0.png",
		"images/main-sheet0.png",
		"images/pause-sheet0.png",
		"images/play-sheet0.png",
		"media/benar.ogg",
		"media/button.ogg",
		"media/salah.ogg",
		"media/anoa.ogg",
		"media/badak jawa.ogg",
		"media/bunga bangkai.ogg",
		"media/bunga edelwis.ogg",
		"media/burung cendrawasih.ogg",
		"media/burung elang jawa.ogg",
		"media/burung maleo.ogg",
		"media/burung merak.ogg",
		"media/kantong semar.ogg",
		"media/komodo.ogg",
		"media/tarsius.ogg",
		"media/trenggiling.ogg",
		"media/kalah.ogg",
		"media/menang.ogg",
		"media/musik.ogg",
		"media/bunga raflesia.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"opening-cerita-game-2.webm"
	]
}